CREATE TABLE IF NOT EXISTS bapjul_location_restaurants (
    id VARCHAR(80) PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    address VARCHAR(400) NOT NULL DEFAULT '',
    floor VARCHAR(40) NOT NULL DEFAULT '',
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    active BOOLEAN NOT NULL DEFAULT TRUE
);
